In [1]:
lines = readlines("input")

601-element Vector{String}:
 "28,82,77,88,95,55,62,21,99,14,30,9,97,92,94,3,60,22,18,86,78,71,61,43,79,33,65,81,26,49,47,51,0,89,57,75,42,35,80,1,46,83,39,53,40,36,54,70,76,38,50,23,67,2,20,87,37,66,84,24,98,4,7,12,44,10,29,5,48,59,32,41,90,17,56,85,96,93,27,74,45,25,15,6,69,16,19,8,31,13,64,63,34,73,58,91,11,68,72,52"
 ""
 "31 88 71 23 61"
 " 4  9 14 93 51"
 "52 50  6 34 55"
 "70 64 78 65 95"
 "12 22 41 60 57"
 ""
 "44 54 26 63 18"
 "32 74 99 52  2"
 " 5 29 13 28 41"
 "60 69 53 61 25"
 "49 59 70 46 48"
 ⋮
 ""
 "51 46  2 26 79"
 "83 52 11 64 22"
 "66 49 61 78 69"
 "70 67 91 10 24"
 "68 63 23 93 35"
 ""
 "42  9 63 56 93"
 "79 59 38 36  7"
 " 6 23 48  0 55"
 "82 45 13 27 83"
 " 1 32  8 40 46"

In [6]:
draws = [parse(Int, x) for x in split(lines[1], ",")];

In [61]:
function fresh_boards()
    boards = []
    for i in 2:6:length(lines)
        mat = zeros(Int,5,5)
        for j in 1:5
            row = [parse(Int,x) for x in split(lstrip(lines[i+j]), r"\s+")]
            mat[j,:] = row
        end
        push!(boards, mat)
    end
    return boards
end

fresh_boards (generic function with 1 method)

In [62]:
boards = fresh_boards()

100-element Vector{Any}:
 [31 88 … 23 61; 4 9 … 93 51; … ; 70 64 … 65 95; 12 22 … 60 57]
 [44 54 … 63 18; 32 74 … 52 2; … ; 60 69 … 61 25; 49 59 … 46 48]
 [26 91 … 23 6; 51 58 … 57 33; … ; 64 66 … 46 9; 16 73 … 74 68]
 [41 31 … 14 82; 4 97 … 49 15; … ; 53 56 … 33 52; 65 68 … 0 94]
 [73 21 … 33 57; 53 10 … 35 0; … ; 49 25 … 78 13; 80 92 … 26 29]
 [97 11 … 46 52; 51 58 … 47 84; … ; 67 94 … 0 70; 65 42 … 44 1]
 [64 70 … 58 56; 18 81 … 59 45; … ; 78 17 … 91 0; 49 98 … 35 9]
 [76 75 … 27 25; 17 92 … 49 28; … ; 11 31 … 14 8; 50 59 … 93 80]
 [3 27 … 11 49; 56 93 … 70 94; … ; 33 28 … 96 9; 42 10 … 78 5]
 [51 64 … 79 31; 73 66 … 70 84; … ; 16 48 … 83 34; 25 98 … 50 19]
 [28 15 … 79 59; 40 76 … 98 12; … ; 19 75 … 73 17; 72 64 … 58 74]
 [24 32 … 57 55; 91 33 … 71 8; … ; 79 35 … 75 23; 38 7 … 27 76]
 [8 93 … 94 39; 21 13 … 83 10; … ; 74 60 … 89 42; 36 69 … 40 67]
 ⋮
 [34 85 … 89 16; 7 12 … 23 47; … ; 99 22 … 38 9; 76 4 … 53 35]
 [51 33 … 56 97; 88 26 … 19 40; … ; 8 42 … 57 5; 83 20 … 29 70]
 [2 41

## Part I

Confirm that there are no negative numbers. Thus -1 can be used as mark and row/col sums of -5 mean bingo. Need to be set to 0 before calculating the score.

In [49]:
minimum([minimum(b) for b in boards])

0

In [60]:
function get_bingo()
    for i in 1:length(draws)
        current = draws[i]
        for b in boards
            b[b .== current] .= -1
            if -5 in sum(b,dims=1) || -5 in sum(b,dims=2)
                print(b)
                b[b .== -1] .= 0
                return sum(b)*current
            end
        end
    end
end

get_bingo()

[89 -1 51 84 27; 47 -1 35 26 -1; -1 -1 -1 -1 -1; 15 -1 65 46 64; 1 -1 16 80 -1]

51034

In [34]:
boards[1]

5×5 Matrix{Int64}:
 31  88  71  23  61
  4   9  14  93  51
 52  50   6  34  55
 70  64  78  65  95
 12  22  41  60  57

In [36]:
boards[1][boards[1] .== 34] .= 0

1-element view(::Vector{Int64}, [18]) with eltype Int64:
 0

In [52]:
172 in sum(boards[1],dims=2)

false

## Part II

In [63]:
boards = fresh_boards()

100-element Vector{Any}:
 [31 88 … 23 61; 4 9 … 93 51; … ; 70 64 … 65 95; 12 22 … 60 57]
 [44 54 … 63 18; 32 74 … 52 2; … ; 60 69 … 61 25; 49 59 … 46 48]
 [26 91 … 23 6; 51 58 … 57 33; … ; 64 66 … 46 9; 16 73 … 74 68]
 [41 31 … 14 82; 4 97 … 49 15; … ; 53 56 … 33 52; 65 68 … 0 94]
 [73 21 … 33 57; 53 10 … 35 0; … ; 49 25 … 78 13; 80 92 … 26 29]
 [97 11 … 46 52; 51 58 … 47 84; … ; 67 94 … 0 70; 65 42 … 44 1]
 [64 70 … 58 56; 18 81 … 59 45; … ; 78 17 … 91 0; 49 98 … 35 9]
 [76 75 … 27 25; 17 92 … 49 28; … ; 11 31 … 14 8; 50 59 … 93 80]
 [3 27 … 11 49; 56 93 … 70 94; … ; 33 28 … 96 9; 42 10 … 78 5]
 [51 64 … 79 31; 73 66 … 70 84; … ; 16 48 … 83 34; 25 98 … 50 19]
 [28 15 … 79 59; 40 76 … 98 12; … ; 19 75 … 73 17; 72 64 … 58 74]
 [24 32 … 57 55; 91 33 … 71 8; … ; 79 35 … 75 23; 38 7 … 27 76]
 [8 93 … 94 39; 21 13 … 83 10; … ; 74 60 … 89 42; 36 69 … 40 67]
 ⋮
 [34 85 … 89 16; 7 12 … 23 47; … ; 99 22 … 38 9; 76 4 … 53 35]
 [51 33 … 56 97; 88 26 … 19 40; … ; 8 42 … 57 5; 83 20 … 29 70]
 [2 41

In [67]:
function get_all_bingos()
    boards = fresh_boards()
    for i in 1:length(draws)
        current = draws[i]
        for b in boards
            b[b .== current] .= -1
            if -5 in sum(b,dims=1) || -5 in sum(b,dims=2)
                print(b,"\t")
                b[b .== -1] .= 0
                print(sum(b)*current,"\n")
                # invalidate board to avoid more bingos
                b .= -2
            end
        end
    end
end

get_all_bingos()

[89 -1 51 84 27; 47 -1 35 26 -1; -1 -1 -1 -1 -1; 15 -1 65 46 64; 1 -1 16 80 -1]	51034
[41 31 12 -1 -1; 4 -1 76 -1 15; 50 -1 72 -1 24; 53 56 -1 -1 52; -1 68 -1 -1 -1]	0
[-1 -1 41 54 -1; 68 5 70 11 -1; 17 -1 73 24 -1; -1 56 -1 75 -1; 48 67 76 64 -1]	66661
[31 -1 -1 23 -1; 4 -1 -1 93 -1; 52 50 6 34 -1; 70 64 -1 -1 -1; 12 -1 41 -1 -1]	27360
[-1 -1 96 67 38; -1 50 20 -1 40; -1 -1 -1 -1 -1; -1 39 66 7 25; 74 72 76 54 16]	42180
[-1 -1 -1 -1 -1; 34 4 -1 -1 27; 25 24 7 6 16; -1 75 38 96 35; 64 15 29 98 -1]	33801
[-1 -1 63 -1 -1; -1 45 -1 -1 -1; 19 15 -1 -1 53; -1 36 -1 -1 -1; 4 85 52 -1 12]	28800
[-1 -1 1 76 -1; -1 35 93 69 -1; 15 17 16 67 -1; -1 38 23 50 -1; 96 54 70 45 -1]	32130
[7 83 -1 17 -1; -1 64 -1 27 -1; 58 44 -1 -1 -1; 38 -1 96 32 -1; -1 -1 -1 70 -1]	24656
[23 36 -1 53 93; -1 50 83 -1 91; 63 69 -1 90 11; -1 -1 59 85 73; -1 -1 -1 -1 -1]	40434
[32 11 -1 56 84; 54 66 38 -1 74; 72 -1 -1 -1 -1; 10 -1 -1 23 -1; -1 -1 -1 -1 -1]	43160
[-1 91 -1 23 6; -1 58 -1 -1 -1; 67 50 -1 -1 48; 64 66 -1 -1