In [11]:
lines = collect.(readlines("input"))

100-element Vector{Vector{Char}}:
 ['9', '9', '8', '7', '6', '3', '2', '1', '2', '3'  …  '8', '9', '9', '8', '7', '6', '5', '4', '3', '2']
 ['9', '8', '7', '6', '5', '4', '1', '0', '1', '9'  …  '9', '8', '9', '9', '8', '9', '3', '2', '1', '0']
 ['9', '9', '9', '7', '6', '3', '2', '1', '2', '3'  …  '6', '7', '8', '9', '9', '8', '9', '3', '2', '3']
 ['9', '8', '7', '6', '5', '4', '3', '2', '9', '9'  …  '7', '8', '9', '9', '8', '7', '8', '9', '3', '9']
 ['9', '9', '8', '7', '6', '5', '4', '9', '8', '6'  …  '4', '7', '8', '9', '7', '6', '7', '9', '9', '8']
 ['8', '7', '9', '8', '7', '6', '9', '8', '7', '5'  …  '5', '6', '7', '8', '9', '5', '7', '9', '8', '7']
 ['7', '6', '5', '9', '8', '7', '9', '9', '7', '6'  …  '8', '9', '8', '9', '3', '4', '9', '7', '9', '6']
 ['8', '5', '4', '2', '9', '8', '9', '9', '8', '3'  …  '7', '8', '9', '3', '2', '9', '8', '6', '5', '4']
 ['7', '6', '2', '1', '0', '9', '5', '6', '9', '9'  …  '8', '9', '5', '2', '1', '4', '9', '7', '6', '5']
 ['9', '8', '7', '3',

In [23]:
heights = parse.(Int,reduce(hcat, lines)) |> transpose

100×100 transpose(::Matrix{Int64}) with eltype Int64:
 9  9  8  7  6  3  2  1  2  3  9  8  9  …  8  7  8  9  9  8  7  6  5  4  3  2
 9  8  7  6  5  4  1  0  1  9  8  7  8     9  6  9  8  9  9  8  9  3  2  1  0
 9  9  9  7  6  3  2  1  2  3  9  6  9     4  5  6  7  8  9  9  8  9  3  2  3
 9  8  7  6  5  4  3  2  9  9  8  5  8     1  6  7  8  9  9  8  7  8  9  3  9
 9  9  8  7  6  5  4  9  8  6  7  4  5     2  3  4  7  8  9  7  6  7  9  9  8
 8  7  9  8  7  6  9  8  7  5  4  3  5  …  3  4  5  6  7  8  9  5  7  9  8  7
 7  6  5  9  8  7  9  9  7  6  3  2  9     6  5  8  9  8  9  3  4  9  7  9  6
 8  5  4  2  9  8  9  9  8  3  2  1  2     5  6  7  8  9  3  2  9  8  6  5  4
 7  6  2  1  0  9  5  6  9  9  3  4  5     8  7  8  9  5  2  1  4  9  7  6  5
 9  8  7  3  2  3  4  5  9  8  7  6  6     9  8  9  9  4  3  2  3  9  8  7  6
 8  7  5  4  3  4  5  6  7  9  8  9  7  …  7  9  9  8  5  4  3  4  5  9  8  7
 9  8  6  7  4  5  6  7  9  4  9  9  8     6  9  8  7  6  5  6  6  7  8  9  8
 9  8  7  

In [30]:
# pad array to avoid edge cases
pheights = zeros(Int, size(heights) .+ 2) .+ 10
pheights[2:end-1,2:end-1] .= heights
pheights

102×102 Matrix{Int64}:
 10  10  10  10  10  10  10  10  10  …  10  10  10  10  10  10  10  10  10
 10   9   9   8   7   6   3   2   1      9   8   7   6   5   4   3   2  10
 10   9   8   7   6   5   4   1   0      9   9   8   9   3   2   1   0  10
 10   9   9   9   7   6   3   2   1      8   9   9   8   9   3   2   3  10
 10   9   8   7   6   5   4   3   2      9   9   8   7   8   9   3   9  10
 10   9   9   8   7   6   5   4   9  …   8   9   7   6   7   9   9   8  10
 10   8   7   9   8   7   6   9   8      7   8   9   5   7   9   8   7  10
 10   7   6   5   9   8   7   9   9      8   9   3   4   9   7   9   6  10
 10   8   5   4   2   9   8   9   9      9   3   2   9   8   6   5   4  10
 10   7   6   2   1   0   9   5   6      5   2   1   4   9   7   6   5  10
 10   9   8   7   3   2   3   4   5  …   4   3   2   3   9   8   7   6  10
 10   8   7   5   4   3   4   5   6      5   4   3   4   5   9   8   7  10
 10   9   8   6   7   4   5   6   7      6   5   6   6   7   8   9   8  10
  

In [32]:
score = 0
for i in 2:size(pheights)[1]-1
    for j in 2:size(pheights)[2]-1
        current = pheights[i,j]
        if current < min(pheights[i-1,j],pheights[i,j-1],pheights[i+1,j],pheights[i,j+1])
            score += current + 1
        end
    end
end
score

475

## Part II

In [37]:
# Get lowpoint locations
lowpoints = []
for i in 2:size(pheights)[1]-1
    for j in 2:size(pheights)[2]-1
        current = pheights[i,j]
        if current < min(pheights[i-1,j],pheights[i,j-1],pheights[i+1,j],pheights[i,j+1])
            push!(lowpoints, (i,j)) # in coordinates with padding
        end
    end
end

In [38]:
lowpoints

205-element Vector{Any}:
 (2, 15)
 (2, 34)
 (2, 64)
 (2, 76)
 (3, 9)
 (3, 25)
 (3, 101)
 (4, 42)
 (4, 80)
 (5, 58)
 (5, 71)
 (5, 89)
 (6, 52)
 ⋮
 (96, 73)
 (97, 98)
 (98, 7)
 (98, 87)
 (99, 22)
 (100, 2)
 (100, 13)
 (100, 91)
 (101, 31)
 (101, 50)
 (101, 62)
 (101, 82)

In [45]:
neighbors((a,b)) = [(a-1,b),(a,b-1),(a+1,b),(a,b+1)]

neighbors (generic function with 1 method)

In [46]:
neighbors((1,2))

4-element Vector{Tuple{Int64, Int64}}:
 (0, 2)
 (1, 1)
 (2, 2)
 (1, 3)

In [73]:
function basin_size(pheights, startpoint)
    basin = Set([startpoint])
    not_basin = Set([])
    to_explore = neighbors(startpoint)
    while length(to_explore) > 0
        pos = pop!(to_explore)
        if pheights[pos[1],pos[2]] .< 9
            push!(basin, pos)
            push!(to_explore, (setdiff(Set(neighbors(pos)),union(basin,not_basin)))...)
        else
            push!(not_basin, pos)
        end
    end
    return length(basin)
end

basin_size (generic function with 1 method)

In [74]:
basin_size(pheights,lowpoints[1])

10

In [77]:
sort([basin_size(pheights, l) for l in lowpoints])

205-element Vector{Int64}:
   2
   2
   2
   2
   2
   2
   2
   2
   3
   3
   3
   3
   3
   ⋮
  87
  88
  89
  89
  90
  91
  93
  96
  98
 101
 102
 106

In [78]:
101*102*106

1092012

### Experiments

just to see how julia works

In [42]:
p = Set([(1,2),(2,3)])

Set{Tuple{Int64, Int64}} with 2 elements:
  (1, 2)
  (2, 3)

In [47]:
q = Set([(1,2),(4,5)])

Set{Tuple{Int64, Int64}} with 2 elements:
  (4, 5)
  (1, 2)

In [50]:
setdiff(q,p)

Set{Tuple{Int64, Int64}} with 1 element:
  (4, 5)

In [53]:
t = [(1,2)]
push!(t, [(2,3),(3,4)]...)
t

3-element Vector{Tuple{Int64, Int64}}:
 (1, 2)
 (2, 3)
 (3, 4)