In [12]:
octo = parse.(Int, reduce(hcat, collect.(readlines("input")))) |> transpose

10×10 transpose(::Matrix{Int64}) with eltype Int64:
 5  2  1  2  1  6  6  7  1  6
 1  5  6  7  3  2  2  5  8  1
 2  2  6  8  4  6  1  5  4  8
 3  4  8  1  5  6  1  7  4  4
 6  2  4  8  3  4  2  2  4  8
 6  5  2  6  6  6  7  3  6  8
 5  6  2  7  3  3  5  7  7  5
 8  1  2  4  5  1  1  7  5  4
 4  6  1  4  1  3  7  6  8  3
 4  7  2  4  5  6  1  1  5  6

In [94]:
# pad border
pad = zeros(Int,12,12) .- Inf
pad[2:11,2:11] .= octo
pad

12×12 Matrix{Float64}:
 -Inf  -Inf   -Inf   -Inf   -Inf   -Inf   …  -Inf   -Inf   -Inf   -Inf   -Inf
 -Inf    5.0    2.0    1.0    2.0    1.0       6.0    7.0    1.0    6.0  -Inf
 -Inf    1.0    5.0    6.0    7.0    3.0       2.0    5.0    8.0    1.0  -Inf
 -Inf    2.0    2.0    6.0    8.0    4.0       1.0    5.0    4.0    8.0  -Inf
 -Inf    3.0    4.0    8.0    1.0    5.0       1.0    7.0    4.0    4.0  -Inf
 -Inf    6.0    2.0    4.0    8.0    3.0  …    2.0    2.0    4.0    8.0  -Inf
 -Inf    6.0    5.0    2.0    6.0    6.0       7.0    3.0    6.0    8.0  -Inf
 -Inf    5.0    6.0    2.0    7.0    3.0       5.0    7.0    7.0    5.0  -Inf
 -Inf    8.0    1.0    2.0    4.0    5.0       1.0    7.0    5.0    4.0  -Inf
 -Inf    4.0    6.0    1.0    4.0    1.0       7.0    6.0    8.0    3.0  -Inf
 -Inf    4.0    7.0    2.0    4.0    5.0  …    1.0    1.0    5.0    6.0  -Inf
 -Inf  -Inf   -Inf   -Inf   -Inf   -Inf      -Inf   -Inf   -Inf   -Inf   -Inf

In [23]:
([1 2; 3 4] .> 2) .& [0 1; 1 0]

2×2 Matrix{Int64}:
 0  0
 1  0

In [28]:
[1 2; 3 4] .> 2

2×2 BitMatrix:
 0  0
 1  1

In [38]:
pos = findfirst(([1 2; 3 4] .> 2) .& BitArray([0 1; 1 0]))
pos

CartesianIndex(2, 1)

In [95]:
function step(pad)
    pad .+= 1
    blinked = BitArray(zeros(12, 12))
    while (sum(pad .> 9) > sum(blinked))
        pos = findfirst((pad .> 9) .& (!).(blinked))
        blinked[pos[1],pos[2]] = true
        pad[(pos[1]-1):(pos[1]+1),(pos[2]-1):(pos[2]+1)] .+= 1
    end
    pad[pad .> 9] .= 0
    return pad
end

step (generic function with 1 method)

In [101]:
step(pad)

12×12 Matrix{Float64}:
 -Inf  -Inf   -Inf   -Inf   -Inf   -Inf   …  -Inf   -Inf   -Inf   -Inf   -Inf
 -Inf    4.0    1.0    1.0    1.0    1.0       7.0    6.0    1.0    5.0  -Inf
 -Inf    1.0    8.0    9.0    9.0    5.0       3.0    7.0    7.0    1.0  -Inf
 -Inf    3.0    6.0    9.0    9.0    3.0       3.0    7.0    5.0    5.0  -Inf
 -Inf    4.0    5.0    0.0    5.0    4.0       3.0    7.0    4.0    4.0  -Inf
 -Inf    3.0    4.0    6.0    0.0    7.0  …    4.0    6.0    4.0    4.0  -Inf
 -Inf    3.0    3.0    6.0    0.0    0.0       8.0    5.0    4.0    4.0  -Inf
 -Inf    3.0    3.0    5.0    0.0    7.0       8.0    5.0    4.0    4.0  -Inf
 -Inf    9.0    3.0    4.0    4.0    4.0       4.0    6.0    5.0    5.0  -Inf
 -Inf    3.0    3.0    3.0    3.0    3.0       0.0    9.0    8.0    3.0  -Inf
 -Inf    3.0    3.0    3.0    3.0    3.0  …    2.0    2.0    4.0    3.0  -Inf
 -Inf  -Inf   -Inf   -Inf   -Inf   -Inf      -Inf   -Inf   -Inf   -Inf   -Inf

In [103]:
pad = zeros(Int,12,12) .- Inf
pad[2:11,2:11] .= octo
blinks = 0
for i in 1:100
    pad = step(pad)
    blinks += sum(pad .== 0)
end
blinks

1719

## Part II

In [106]:
pad = zeros(Int,12,12) .- Inf
pad[2:11,2:11] .= octo
steps = 0
while true
    steps += 1
    pad = step(pad)
    if sum(pad .== 0) == 100
        break
    end
end
steps

232