In [1]:
lines = readlines("input")

102-element Vector{String}:
 "##.####..##...##..##.##.###....#..##..#.####.#####..##.#.##.#..#.#####.#.#.....#.####.##.......#.###.#.#..#.##.#.#....####.###..#.####.....##.##.#.#.#.###..#.#..##.####..####...####.#......#...####.#.....##.##.#.#####.#.##...###.#.##.#.#.###.#.####...#####..#.#....######.##.#.###....##...##.#####..##.#.###....#...#...#.#.###.#...##..##........###.#####.###.##....#.##.##..###..#.####....##...###.#####.##..#...###.######.#..#.#...##..#.#####.###.#...#....#.##.#.#.#..#...#####.#..###..#.#...#.#.###.#.#..###.#."
 ""
 "..#.####..###.#.###.##..#...##.#.#..###........#.##...##.#.#...########.#.##...#..##.#.##..##...#.##"
 "#####....#..#.#.#...#.#.#..###.##...#.##.#.#...#.#.##.##.......#....#..###.##..#####..#.#.....###..#"
 ".#.##..#.....#.#.#.#.##.#.#....###.####.#.##...#..##..#.#..#.#####....#.#...##.##...#..#.##...##...#"
 "##...####....#...##..##.#..##..####.###.#....#.#.......##..#....#.##..##..##.#..##.#..##.###.#..###."
 "...##.#..#..##..#.#..#.#.####.....

In [5]:
using Underscores

In [9]:
enhance = @_ lines[1] |> collect |> replace(__, '#'=>1, '.'=>0)

512-element Vector{Any}:
 1
 1
 0
 1
 1
 1
 1
 0
 0
 1
 1
 0
 0
 ⋮
 0
 1
 0
 1
 0
 0
 1
 1
 1
 0
 1
 0

In [32]:
field = lines[3:end] .|> collect |> x->replace.(x, '#'=>1, '.'=>0) |> x->reduce(hcat, x) |> transpose

100×100 transpose(::Matrix{Any}) with eltype Any:
 0  0  1  0  1  1  1  1  0  0  1  1  1  …  1  0  0  1  1  0  0  0  1  0  1  1
 1  1  1  1  1  0  0  0  0  1  0  0  1     1  0  0  0  0  0  1  1  1  0  0  1
 0  1  0  1  1  0  0  1  0  0  0  0  0     0  1  1  0  0  0  1  1  0  0  0  1
 1  1  0  0  0  1  1  1  1  0  0  0  0     0  1  1  1  0  1  0  0  1  1  1  0
 0  0  0  1  1  0  1  0  0  1  0  0  1     0  1  1  0  0  0  1  0  0  1  0  1
 0  0  1  0  0  1  1  0  0  0  0  0  1  …  1  0  1  0  0  0  0  0  0  0  1  1
 1  0  1  0  0  0  0  1  0  1  0  1  1     1  0  0  1  0  1  1  1  1  0  0  1
 0  1  1  0  0  0  1  1  0  0  1  1  0     0  1  1  1  0  0  1  1  1  0  0  0
 1  1  0  0  0  0  0  0  1  1  0  0  0     0  1  1  0  0  0  0  1  0  1  0  1
 0  0  1  0  1  0  1  0  1  1  0  1  1     1  1  0  1  1  1  0  1  0  1  1  0
 0  1  1  1  0  0  0  0  1  1  1  1  1  …  0  1  1  1  1  0  0  0  0  0  1  0
 1  0  0  0  0  0  1  1  0  1  1  0  0     1  1  0  1  1  0  1  0  1  0  1  0
 0  0  0  1  0

In [21]:
function pad_zeros(A,n)
    s = size(A)
    B = zeros(Int, s[1]+2*n, s[2]+2*n)
    B[n+1:n+s[1], n+1:n+s[2]] .= A
    return B
end

pad_zeros (generic function with 1 method)

In [24]:
pad_zeros([1 2; 3 4], 3)

8×8 Matrix{Int64}:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  1  2  0  0  0
 0  0  0  3  4  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

In [33]:
padded_field = pad_zeros(field, 5)

110×110 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  1  0  1  1  1  1  …  0  0  0  1  0  1  1  0  0  0  0  0
 0  0  0  0  0  1  1  1  1  1  0  0  0     0  1  1  1  0  0  1  0  0  0  0  0
 0  0  0  0  0  0  1  0  1  1  0  0  1     0  1  1  0  0  0  1  0  0  0  0  0
 0  0  0  0  0  1  1  0  0  0  1  1  1     1  0  0  1  1  1  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  0  1  0     0  1  0  0  1  0  1  0  0  0  0  0
 0  0  0  0  0  0  0  1  0  0  1  1  0  …  0  0  0  0  0  1  1  0  0  0  0  0
 0  0  0  0  0  1  0  1  0  0  0  0  1     1  1  1  1  0  0  1  0  0  0  0  0
 0  0  0  0  0  0  1  1  0  0  0  1  1   

In [31]:
m = [1 2 3; 4 5 6; 7 8 9]
m'[7]

7

In [34]:
function pos2index(field, pos)
    area = field[pos[1]:pos[1]+2,pos[2]:pos[2]+2]
    ind = 0
    for i in 1:9
        ind += 2^(9-i)*area'[i]
    end
    return ind
end

pos2index (generic function with 1 method)

In [35]:
pos2index(field, (1,1))

122

In [40]:
function step_field(field)
    new_field = zeros(Int, size(field)[1]-2, size(field)[2]-2)
    for i in 1:size(field)[1]-2
        for j in 1:size(field)[2]-2
            new_field[i,j] = enhance[pos2index(field, (i,j))+1]
        end
    end
    return new_field
end

step_field (generic function with 1 method)

In [41]:
after1 = step_field(padded_field)

108×108 Matrix{Int64}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  0  1  1  0  0  1  1     1  1  1  1  0  1  1  1  1  1  1  1
 1  1  1  1  1  1  0  1  0  1  0  1  0     1  0  1  1  1  0  1  0  0  1  1  1
 1  1  1  0  1  0  1  1  1  1  0  0  1  …  1  1  0  0  1  1  0  1  1  1  1  1
 1  1  1  1  0  0  0  0  1  0  1  0  0     1  0  1  1  1  0  0  0  0  1  1  1
 1  1  1  0  0  0  1  1  1  1  0  0  1     1  1  1  1  0  1  0  1  1  1  1  1
 1  1  1  0  0  0  1  0  1  0  0  1  0     0  0  1  0  0  0  0  1  0  1  1  1
 1  1  1  1  0  0  1  0  0  0  1  1  1     1  1  0  0  0  1  1  1  1  1  1  1
 1  1  1  0  0  0  0  1  0  1  1  1  0  …  0  1  0  1  0  0  0  1  0  1  1  1
 1  1  1  1  1  1  1  0  1  0  0  1  1     1  0  1  1  0  1  1  1  1  1  1  1
 1  1  1  0  0  0  1  0  0  1  1  0  0   

In [42]:
after2 = step_field(after1)

106×106 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  0  1  1  1  0  1  0  0     0  0  0  0  1  0  1  0  0  0  0  0
 0  0  0  0  0  1  1  1  1  0  1  0  1     1  1  0  1  1  0  1  1  1  0  1  0
 0  1  0  1  0  0  1  0  1  1  0  0  0     1  1  0  1  1  1  1  1  1  0  1  0
 0  1  0  0  0  0  0  0  0  0  1  0  1     0  1  0  1  0  1  0  0  0  1  1  0
 0  1  0  0  1  1  0  0  0  0  1  1  1  …  1  1  0  0  0  1  1  1  1  0  1  0
 0  0  1  0  1  1  1  0  0  1  1  0  0     0  1  0  0  0  0  1  1  1  1  1  0
 0  1  1  1  1  1  0  1  1  1  1  1  0     1  1  1  0  1  1  1  1  1  1  1  0
 0  1  0  0  0  1  0  1  1  1  0  0  1     1  0  0  1  1  0  1  1  0  1  1  0
 0  1  1  0  1  1  1  1  0  0  1  1  1     1  0  1  1  1  1  1  0  0  1  1  0
 0  1  0  0  1  0  1  0  1  1  1  0  0  …  1  0  0  1  1  0  0  0  0  0  1  0
 0  0  0  0  0  0  0  0  0  0  0  1  0     1  1  0  1  1  0  0  1  0  0  1  0
 0  1  0  0  1  0  1  1  0  0  0  0  1   

In [43]:
sum(after2)

5846

## Part II

In [44]:
using Lazy

In [49]:
padded_alot = pad_zeros(field, 100)

300×300 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0   

In [50]:
field_steps = iterated(step_field, padded_alot)

List: ([0 0 … 0 0; 0 0 … 0 0; … ; 0 0 … 0 0; 0 0 … 0 0] [1 1 … 1 1; 1 1 … 1 1; … ; 1 1 … 1 1; 1 1 … 1 1] [0 0 … 0 0; 0 0 … 0 0; … ; 0 0 … 0 0; 0 0 … 0 0] [1 1 … 1 1; 1 1 … 1 1; … ; 1 1 … 1 1; 1 1 … 1 1] [0 0 … 0 0; 0 0 … 0 0; … ; 0 0 … 0 0; 0 0 … 0 0] [1 1 … 1 1; 1 1 … 1 1; … ; 1 1 … 1 1; 1 1 … 1 1] [0 0 … 0 0; 0 0 … 0 0; … ; 0 0 … 0 0; 0 0 … 0 0] [1 1 … 1 1; 1 1 … 1 1; … ; 1 1 … 1 1; 1 1 … 1 1] [0 0 … 0 0; 0 0 … 0 0; … ; 0 0 … 0 0; 0 0 … 0 0] [1 1 … 1 1; 1 1 … 1 1; … ; 1 1 … 1 1; 1 1 … 1 1] [0 0 … 0 0; 0 0 … 0 0; … ; 0 0 … 0 0; 0 0 … 0 0] …)

In [51]:
sum(field_steps[3])

5846

In [52]:
sum(field_steps[51])

21149