In [2]:
lines = readlines("input")
template = lines[1]

"VNVVKSNNFPBBBVSCVBBC"

In [3]:
using DataStructures

Use `DefaultDict` in case there are some pairs with no rule attached (insert "" in this case). &rarr; retrospectively, this was not necessary

In [4]:
rules = DefaultDict(()->"")

DefaultDict{Any, Any, var"#1#2"}()

In [5]:
s,t = split(lines[3], " -> ")

2-element Vector{SubString{String}}:
 "SV"
 "C"

In [6]:
for l in lines[3:end]
    s,t = split(l, " -> ")
    rules[s] = t
end

In [7]:
rules

DefaultDict{Any, Any, var"#1#2"} with 100 entries:
  "FN" => "H"
  "PO" => "B"
  "BC" => "V"
  "KF" => "S"
  "CC" => "S"
  "BV" => "B"
  "OP" => "S"
  "PF" => "S"
  "BB" => "H"
  "VN" => "F"
  "NH" => "O"
  "PP" => "B"
  "NB" => "N"
  "SF" => "P"
  "CS" => "K"
  "PN" => "P"
  "CF" => "K"
  "NO" => "B"
  "KV" => "V"
  "OS" => "S"
  "VH" => "N"
  "PS" => "P"
  "BS" => "O"
  "NP" => "N"
  "HO" => "C"
  ⋮    => ⋮

In [8]:
"a" * "" * "b"

"ab"

In [9]:
function step(template)
    after = template[1]
    for i in 2:length(template)
        after *= rules[template[(i-1):i]] * template[i]
    end
    return after
end

step (generic function with 1 method)

In [10]:
step(template)

"VFNHVOVKKVSNNVNCFHPSBHBHBBVNSBCOVVBHBVC"

In [11]:
template

"VNVVKSNNFPBBBVSCVBBC"

In [12]:
step10 = template
for i in 1:10
    step10 = step(step10)
end
step10

"VFFKFHKSFHHBKVSPFHHSHVBSKVVNSCPSFHHSHHSOHFVVBOSKKVVOVFNKSBCHPPSPFHHSHHSOHSHHSFOCHPFNVOVVBKOSSKKNKVVOVFONVFFHNFKVSNBVCBHSPBPPSCPSFHHSHHSOHSHHSFOCHHSOHSHHSPFFOKCBHSPSFHNHVFONVOVVBSKHOSSCSKKNKHNFKVVOVFONVFFFOSNHVFFKFHHVNCFHKVVNSNNNBBVSCSBBHHSCPSBVPBPPSBCHPPSPFHHSHHSOHSHHSFOCHHSOHSHHSPFFOKCBHSHHSFOCHHSOHSHHSCPSFKFFONKVCSBBHHSCPPSPFHHVNOHFVFFFOSNHVFONVOVVBOSKKCHCOSSCSBCKSKKNKHNFKCHVNCFHKVVOVFONVFFFOSNHVFFKFKFFOSSNNOHFVFFKFHKSFHHSHFVFNCCKFHHBKVVOVFNKSNNVNVNNBHBBVNSBCKSNBHBBHSHHSBCHPPSNBBVCPSBVPBPPSNBVCBHSPBPPSCPSFHHSHHSOHSHHSFOCHHSOHSHHSPFFOKCBHSHHSFOCHHSOHSHHSCPSFKFFONKVCSBBHHSOHSHHSPFFOKCBHSHHSFOCHHSOHSHHSBCHPPSPFHKSFKFFOSNFKVVSCKSNBHBBHSHHSFOCHHSOHSHHSCPSFKFFONKVCSBBHHSOHSHHSPFFOKCBHSHHSFOCHHSOHSHHSNBVCBHSPBPPSCPSFHHBKVSPFHKSFKFFOSSNNCFHKVVOVNSBCFKVSNNNBBHVBHBBHSHHSFOCHHSOHSHHSNNNBBVSCSBBHHSCPPSNBBVCPSBVPBPPSNBVCBHSPBPPSCPSFHHSHHSOHSHHSFOCHSPSFHNHVFFKFHHVNVNNBSKHONKVCSBBHHSCPPSPFHHVNOHFVFFKFHKSFHHBKVSPFHHSHVBSKVVNSCPSFHHSHHSOHFVVBOSKKVVOVFNKSBCHPPSPFHHSHHSOHSHHSFOCHHSOHSHHSPFFOKCBHHSCPPS

In [13]:
using StatsBase

In [14]:
sort(countmap(collect(step10)), byvalue=true)

OrderedDict{Char, Int64} with 10 entries:
  'C' => 997
  'P' => 1077
  'O' => 1208
  'K' => 1237
  'N' => 1790
  'B' => 2054
  'V' => 2381
  'S' => 2540
  'F' => 2555
  'H' => 3618

In [15]:
3618-997

2621

In [16]:
cm = countmap(collect(step10))
maximum(values(cm)) - minimum(values(cm))

2621

## Part II

This does not work. It takes forever. My estimation is (maybe even far) more than a year. Damn exponential growth 😬

In [37]:
step40 = template
for i in 1:40
    step40 = step(step40)
end

LoadError: InterruptException:

In [ ]:
cm = countmap(collect(step40))
maximum(values(cm)) - minimum(values(cm))

### Alternative approach

iteratively count each letter after a certain number of steps

In [17]:
unique(collect(template))

8-element Vector{Char}:
 'V': ASCII/Unicode U+0056 (category Lu: Letter, uppercase)
 'N': ASCII/Unicode U+004E (category Lu: Letter, uppercase)
 'K': ASCII/Unicode U+004B (category Lu: Letter, uppercase)
 'S': ASCII/Unicode U+0053 (category Lu: Letter, uppercase)
 'F': ASCII/Unicode U+0046 (category Lu: Letter, uppercase)
 'P': ASCII/Unicode U+0050 (category Lu: Letter, uppercase)
 'B': ASCII/Unicode U+0042 (category Lu: Letter, uppercase)
 'C': ASCII/Unicode U+0043 (category Lu: Letter, uppercase)

In [18]:
unique(values(rules))

10-element Vector{Any}:
 "H"
 "B"
 "V"
 "S"
 "F"
 "O"
 "N"
 "P"
 "K"
 "C"

Rules contain all possible pairs.
So for each pair calculate the number of each letter after 10 steps

In [19]:
using Lazy

In [20]:
itstep = iterated(step, template)

List: (VNVVKSNNFPBBBVSCVBBC VFNHVOVKKVSNNVNCFHPSBHBHBBVNSBCOVVBHBVC VFFHNOHFVFONVKKNKVVNSNNVNHVFNCCKFHHSPPSNBBHVBBHVBHBBVFNKSNBVCOONVOVVBBHVBBVSC VFFKFHHVNBOCHPFNVFFFOSNHVKKNKHNFKVVOVFNKSNNVNHVFNOHFVFFHNCCSCFKSFHHSHHSCPBPPSNNNBHBBHFVVBHBBHFVVBBHVBHBBVFFHNFKVSNNNBBVSCOOCOSNHVFONVOVVBHBBHFVVBHBBVNSBC VFFKFHKSFHHSHFVFNNBKOKCBHSPSFHNHVFFKFKFFOSSNNOHFVKKNKHNFKCHVNCFHKVVOVFONVFFHNFKVSNNVNHVFNOHFVFFHNBOCHPFNVFFKFHHVNCCSCKSBCKFHKVSPFHHSHHSOHSHHSBCHPSBVPBPPSNNVNVNNBBHVBHBBHPFNVOVVBBHVBHBBHPFNVOVVBHBBHFVVBBHVBHBBVFFKFHHVNCFHKVVNSNNVNVNNBHBBVNSBCOOCOKCOOSSNNOHFVFFFOSNHVFONVOVVBBHVBHBBHPFNVOVVBBHVBHBBVFNKSNBVC VFFKFHKSFHHBKVSPFHHSHHSOHPFNVFFHNVNNBSKHONKVCSBBHHSCPPSPFHHVNOHFVFFKFHKSFHKSFKFFOSSCSNNVNBOCHPFNVKKNKHNFKCHVNCFHKVCBHFVFNCCKFHHBKVVOVFONVFFFOSNHVFFKFHHVNCFHKVVNSNNVNHVFNOHFVFFHNBOCHPFNVFFKFHHVNNBKOKCBHSPSFHNHVFFKFHKSFHHSHFVFNCCSCKSBCFKVSNBVCFKSFHHBKVVNSCPSFHHSHHSOHSHHSFOCHHSOHSHHSNBVCBHSPPSNBBVCPSBVPBPPSNNVNHVFNHVFNVNNBHBBHFVVBBHVBHBBHSPSFHNHVFONVOVVBHBBHFVVBBHVBHBBHSPSFHNHVFONVOVVBBHVBHBBHP

In [21]:
itstep[10] |> collect |> countmap |> sort |> values |> collect

10-element Vector{Int64}:
 1035
  481
 1318
 1801
  621
  894
  607
  518
 1240
 1214

In [22]:
letter_counts_10 = Dict()
for pair in keys(rules)
    letter_counts_10[pair] = iterated(step, pair)[11] |> collect |> countmap |> sort |> values |> collect # 11 because element 1 is x not f(x)
end
letter_counts_10

Dict{Any, Any} with 100 entries:
  "FN" => [95, 66, 112, 232, 60, 65, 66, 73, 183, 73]
  "PO" => [130, 64, 125, 152, 71, 131, 60, 50, 100, 142]
  "BC" => [144, 31, 158, 200, 51, 83, 63, 46, 93, 156]
  "KF" => [127, 47, 132, 170, 65, 118, 43, 62, 127, 134]
  "CC" => [85, 44, 170, 200, 75, 93, 62, 47, 119, 130]
  "BV" => [178, 28, 138, 194, 30, 77, 67, 60, 96, 157]
  "OP" => [123, 31, 160, 187, 63, 133, 52, 22, 85, 169]
  "PF" => [212, 39, 84, 160, 20, 155, 23, 86, 91, 155]
  "BB" => [148, 40, 136, 191, 46, 85, 60, 66, 121, 132]
  "VN" => [78, 63, 123, 217, 68, 66, 73, 70, 177, 90]
  "NH" => [100, 60, 154, 167, 78, 117, 64, 30, 105, 150]
  "PP" => [166, 30, 135, 195, 37, 119, 43, 61, 89, 150]
  "NB" => [82, 55, 131, 217, 69, 89, 59, 67, 151, 105]
  "SF" => [185, 36, 109, 180, 32, 141, 32, 63, 97, 150]
  "CS" => [66, 62, 160, 181, 94, 78, 69, 50, 160, 105]
  "PN" => [201, 35, 104, 168, 27, 144, 28, 75, 83, 160]
  "CF" => [105, 60, 136, 175, 73, 100, 58, 59, 149, 110]
  "NO" => [94, 70, 13

In [23]:
# check letter completeness
unique([length(x) for x in values(letter_counts_10)])

1-element Vector{Int64}:
 10

As an exercise check part I with this approach 😂

In [24]:
all_letters = first.(sort(unique(values(rules)))) # first is to convert single character String to Char

10-element Vector{Char}:
 'B': ASCII/Unicode U+0042 (category Lu: Letter, uppercase)
 'C': ASCII/Unicode U+0043 (category Lu: Letter, uppercase)
 'F': ASCII/Unicode U+0046 (category Lu: Letter, uppercase)
 'H': ASCII/Unicode U+0048 (category Lu: Letter, uppercase)
 'K': ASCII/Unicode U+004B (category Lu: Letter, uppercase)
 'N': ASCII/Unicode U+004E (category Lu: Letter, uppercase)
 'O': ASCII/Unicode U+004F (category Lu: Letter, uppercase)
 'P': ASCII/Unicode U+0050 (category Lu: Letter, uppercase)
 'S': ASCII/Unicode U+0053 (category Lu: Letter, uppercase)
 'V': ASCII/Unicode U+0056 (category Lu: Letter, uppercase)

In [25]:
# helper function to get a count vector from a string with (potentially) missing letters
function manual_letter_count(seq)
    counts = zeros(Int, 10)
    cm = seq |> collect |> countmap
    for i in 1:10
        if haskey(cm, all_letters[i])
            counts[i] = cm[all_letters[i]]
        end
    end
    return counts
end

manual_letter_count (generic function with 1 method)

In [26]:
manual_letter_count(template)

10-element Vector{Int64}:
 5
 2
 1
 0
 1
 3
 0
 1
 2
 5

In [27]:
function total_letter_counts(seq, counts)
    total = zeros(Int, 10)
    for i in 2:length(seq)
        total .+= counts[seq[(i-1):i]]
    end
    # now the overlapping characters are counted twice
    total .-= manual_letter_count(seq[2:(end-1)])
    return total
end

total_letter_counts (generic function with 1 method)

In [28]:
tlc = total_letter_counts(template, letter_counts_10)
maximum(tlc) - minimum(tlc)

2621

Perfect! So now iterate the counting for 20, 30 and 40 steps

In [29]:
total_letter_counts(iterated(step, "PK")[11], letter_counts_10)

10-element Vector{Int64}:
 113658
  54903
 134150
 197137
  65930
  97758
  61740
  58827
 141908
 122566

In [30]:
letter_counts_20 = Dict()
for pair in keys(rules)
    letter_counts_20[pair] = total_letter_counts(iterated(step, pair)[11], letter_counts_10)
end
letter_counts_20

Dict{Any, Any} with 100 entries:
  "FN" => [118838, 52658, 133832, 197618, 63742, 99511, 59455, 58288, 139866, 1…
  "PO" => [112596, 55977, 134165, 194930, 66589, 98546, 63455, 57978, 141114, 1…
  "BC" => [119537, 53798, 131710, 195440, 63648, 99696, 59956, 59933, 140892, 1…
  "KF" => [116549, 53869, 133448, 197672, 64700, 98421, 60123, 59426, 141195, 1…
  "CC" => [114735, 55627, 132489, 195455, 66376, 99887, 60332, 58367, 143248, 1…
  "BV" => [122987, 51923, 132435, 195585, 61743, 100226, 59536, 60321, 137409, …
  "OP" => [113649, 55981, 131540, 196683, 66136, 97211, 61331, 60183, 145729, 1…
  "PF" => [122974, 50880, 132907, 201185, 59825, 96271, 60271, 61961, 137518, 1…
  "BB" => [120440, 52702, 133085, 196302, 63040, 99995, 59667, 59479, 138415, 1…
  "VN" => [117065, 53257, 134463, 196724, 64784, 100190, 59673, 57682, 139948, …
  "NH" => [111121, 56759, 133610, 194090, 67948, 99119, 62634, 57800, 143357, 1…
  "PP" => [120547, 53203, 131465, 198145, 62210, 97987, 60347, 60810, 140572

In [31]:
letter_counts_30 = Dict()
for pair in keys(rules)
    letter_counts_30[pair] = total_letter_counts(iterated(step, pair)[11], letter_counts_20)
end
letter_counts_30

Dict{Any, Any} with 100 entries:
  "FN" => [119538749, 55093664, 136750213, 201532206, 66327753, 101420709, 6172…
  "PO" => [118714050, 55538644, 136928242, 200931125, 66815891, 101725809, 6220…
  "BC" => [119543068, 55052090, 136910428, 201494319, 66297035, 101496742, 6182…
  "KF" => [119440267, 55168981, 136804502, 201435226, 66385884, 101548677, 6182…
  "CC" => [118983848, 55238027, 137013139, 201423486, 66614579, 101448876, 6189…
  "BV" => [119889224, 55003301, 136749643, 201504580, 66103409, 101521746, 6180…
  "OP" => [119193901, 55135527, 137069831, 201399300, 66523938, 101603679, 6183…
  "PF" => [120469932, 54912222, 136511313, 201504825, 65821523, 101684577, 6171…
  "BB" => [119645180, 55105679, 136753382, 201466748, 66249328, 101503027, 6183…
  "VN" => [119276501, 55192968, 136799667, 201483421, 66465139, 101411693, 6179…
  "NH" => [118544031, 55489320, 137062983, 201066125, 66898168, 101636798, 6211…
  "PP" => [119880674, 54992434, 136786010, 201493445, 66122904, 101567201, 6

In [32]:
letter_counts_40 = Dict()
for pair in keys(rules)
    letter_counts_40[pair] = total_letter_counts(iterated(step, pair)[11], letter_counts_30)
end
letter_counts_40

Dict{Any, Any} with 100 entries:
  "FN" => [122213531856, 56504648108, 140121268854, 206251593883, 68028636149, …
  "PO" => [122040565297, 56583931526, 140145096044, 206168731409, 68125796040, …
  "BC" => [122198318314, 56523978803, 140109029573, 206229859750, 68037847221, …
  "KF" => [122175910078, 56525248342, 140120284125, 206232662861, 68048768660, …
  "CC" => [122138738431, 56541169025, 140124758983, 206218402994, 68073739762, …
  "BV" => [122231427927, 56512902706, 140105238732, 206235047724, 68016761445, …
  "OP" => [122145053226, 56542057457, 140114753802, 206222558885, 68068361298, …
  "PF" => [122270722441, 56493678077, 140100491948, 206253215705, 67989650462, …
  "BB" => [122204070083, 56518678179, 140114745504, 206231981954, 68032838643, …
  "VN" => [122182818392, 56516072519, 140128123756, 206241817912, 68046593747, …
  "NH" => [122045938334, 56579693681, 140141715871, 206180308033, 68125012631, …
  "PP" => [122222374368, 56514629386, 140104918297, 206235733158, 6802204262

In [33]:
tlc = total_letter_counts(template, letter_counts_40)
maximum(tlc) - minimum(tlc)

2843834241366

In [37]:
zip(all_letters, tlc) |> collect

10-element Vector{Tuple{Char, Int64}}:
 ('B', 2320648606516)
 ('C', 1074264218824)
 ('F', 2662445968068)
 ('H', 3918098460190)
 ('K', 1293349712552)
 ('N', 1975295538949)
 ('O', 1203571008272)
 ('P', 1169822018203)
 ('S', 2807066214377)
 ('V', 2466159181794)