In [12]:
using CSV, DataFrames

In [133]:
data = CSV.read("input", DataFrame, header=[:x1, :y1x2, :y2])

500×3 DataFrame
 Row │ x1     y1x2        y2    
     │ Int64  String15    Int64 
─────┼──────────────────────────
   1 │    88  177 -> 566    655
   2 │   346  264 -> 872    264
   3 │   409  631 -> 506    534
   4 │   300  216 -> 300    507
   5 │    80  370 -> 193    483
   6 │    85  283 -> 85     483
   7 │   589  528 -> 968    528
   8 │   936  83 -> 936     909
   9 │    21  41 -> 907     927
  10 │   868  624 -> 868    490
  11 │   954  972 -> 51      69
  ⋮  │   ⋮        ⋮         ⋮
 491 │   651  511 -> 651    523
 492 │   974  16 -> 518     472
 493 │    98  27 -> 679      27
 494 │   727  896 -> 20     896
 495 │   953  557 -> 845    449
 496 │   219  60 -> 755     596
 497 │    34  868 -> 358    868
 498 │   900  908 -> 61      69
 499 │    56  108 -> 391    108
 500 │   661  661 -> 613    661
                479 rows omitted

In [134]:
data[:,:y1]=[parse(Int,i[1]) for i in [split(i," -> ") for i in data[:,:y1x2]]];
data[:,:x2]=[parse(Int,i[2]) for i in [split(i," -> ") for i in data[:,:y1x2]]];
data[1:10,:]

10×5 DataFrame
 Row │ x1     y1x2        y2     y1     x2    
     │ Int64  String15    Int64  Int64  Int64 
─────┼────────────────────────────────────────
   1 │    88  177 -> 566    655    177    566
   2 │   346  264 -> 872    264    264    872
   3 │   409  631 -> 506    534    631    506
   4 │   300  216 -> 300    507    216    300
   5 │    80  370 -> 193    483    370    193
   6 │    85  283 -> 85     483    283     85
   7 │   589  528 -> 968    528    528    968
   8 │   936  83 -> 936     909     83    936
   9 │    21  41 -> 907     927     41    907
  10 │   868  624 -> 868    490    624    868

In [135]:
select!(data, [:x1, :y1, :x2, :y2])
data[1:10,:]

10×4 DataFrame
 Row │ x1     y1     x2     y2    
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │    88    177    566    655
   2 │   346    264    872    264
   3 │   409    631    506    534
   4 │   300    216    300    507
   5 │    80    370    193    483
   6 │    85    283     85    483
   7 │   589    528    968    528
   8 │   936     83    936    909
   9 │    21     41    907    927
  10 │   868    624    868    490

In [136]:
data = data .+ 1;

Only keep horizontal and vertical rows

In [137]:
hv = filter(row->(row.x1==row.x2 || row.y1==row.y2), data);
hv#[1:10,:]

338×4 DataFrame
 Row │ x1     y1     x2     y2    
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │   347    265    873    265
   2 │   301    217    301    508
   3 │    86    284     86    484
   4 │   590    529    969    529
   5 │   937     84    937    910
   6 │   869    625    869    491
   7 │   682    223    682     33
   8 │   597    558    385    558
   9 │   831    946    831    211
  10 │   147     18    583     18
  11 │   924    865    924    855
  ⋮  │   ⋮      ⋮      ⋮      ⋮
 329 │    15    596    610    596
 330 │   577    626    577    431
 331 │   855    419    855    295
 332 │   216    775    288    775
 333 │   652    512    652    524
 334 │    99     28    680     28
 335 │   728    897     21    897
 336 │    35    869    359    869
 337 │    57    109    392    109
 338 │   662    662    614    662
                  317 rows omitted

In [138]:
maximum(eachrow(hv))

DataFrameRow
 Row │ x1     y1     x2     y2    
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
 319 │   988    772    976    772

In [139]:
oceanmap = zeros(Int,1000,1000)

1000×1000 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0 

In [140]:
for r in eachrow(hv)
    if r.y2>r.y1 || r.x2>r.x1
        oceanmap[r.y1:r.y2,r.x1:r.x2] .+= 1
    else
        oceanmap[r.y2:r.y1,r.x2:r.x1] .+= 1
    end
end

In [141]:
oceanmap#[140:160,20:40]

1000×1000 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0 

In [142]:
sum(oceanmap .> 1)

5835

Solution: 5835

## Part II

In [143]:
diag = filter(row->(row.x1!=row.x2 && row.y1!=row.y2), data);

In [144]:
for r in eachrow(diag)
    xs = r.x1:sign(r.x2-r.x1):r.x2
    ys = r.y1:sign(r.y2-r.y1):r.y2
    for (x,y) in zip(xs,ys)
        oceanmap[y,x] += 1
    end
end

In [145]:
oceanmap[1:10,1:10]

10×10 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [146]:
sum(oceanmap .> 1)

17013